### ISSUE TITLE
[Stall-Disguises] obliquemc.common.disguises.Disguises$Companion.addDisguis

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#1008]
"Server thread" #20 prio=5
RUNNABLE
	at com.pixelmonmod.pixelmon.enums.EnumSpecies.randomPoke(EnumSpecies.java:1329)
	at com.pixelmonmod.pixelmon.enums.EnumSpecies.randomPoke(EnumSpecies.java:1306)
	at com.pixelmonmod.pixelmon.entities.pixelmon.specs.Type2Spec.randomPokeType(Type2Spec.java:103)
	at com.pixelmonmod.pixelmon.entities.pixelmon.specs.Type2Spec.apply(Type2Spec.java:74)
	at com.pixelmonmod.pixelmon.api.pokemon.PokemonSpec.create(PokemonSpec.java:627)
	at net.obliquemc.common.disguises.Disguises$Companion.addDisguise(Disguises.kt:45)
	at net.obliquemc.common.disguises.command.DisguiseCommand.execute(DisguiseCommand.kt:106)
	at net.obliquemc.common.api.command.IObliqueCommand$DefaultImpls.run(IObliqueCommand.kt:18)
	at net.obliquemc.common.disguises.command.DisguiseCommand.run(DisguiseCommand.kt:24)
	at com.cable.library.command.IAnnotatedCommandExecutor$toCommand$1.func_184881_a(Command.kt:233)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
	at net.minecraft.command.CommandHandler.accessor$tryExecuteCommand(CommandHandler.java)
	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:161)
	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:146)
	at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219)
	at net.minecraft.network.PacketThreadUtil$1.redirect$zlf000$impl$redirectToPhaseTracker(SourceFile:540)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)
	at net.minecraft.server.MinecraftServer.redirect$zjj000$onRun(MinecraftServer.java:4682)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
	- locked java.util.ArrayDeque@6ad42763
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Hiroku** [comment]
If this were the cause of the stall, it would come from Pixelmon's random spec which seems very unlikely. This is likely to be a coincidence, there's no looping going on here
