### ISSUE TITLE
[8.0.1] Quests interact

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#549]
`[16:05:25] [Server thread/ERROR] [FML]: Exception caught during firing event com.pixelmonmod.pixelmon.api.events.NPCChatEvent@3c99c53c:
java.lang.NoSuchFieldError: npc
	at com.hiroku.common.quests.listeners.PixelmonHandler.onChatNPC(PixelmonHandler.java:66) ~[PixelmonHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_PixelmonHandler_onChatNPC_NPCChatEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
	at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.interactWithNPC(NPCChatting.java:142) [NPCChatting.class:?]
	at com.pixelmonmod.pixelmon.entities.npcs.EntityNPC.func_184645_a(EntityNPC.java:410) [EntityNPC.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) [vq.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) [aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:3188) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.2.2]
	at net.minecraft.network.PacketThreadUtil$1.redirect$zld000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.2]
	at net.minecraft.server.MinecraftServer.redirect$zjh000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[16:05:25] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[16:05:25] [Server thread/ERROR] [FML]: 0: NORMAL
[16:05:25] [Server thread/ERROR] [FML]: 1: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@1eb1c437 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
[16:05:25] [Server thread/ERROR] [FML]: 2: ASM: com.hiroku.common.quests.listeners.PixelmonHandler@15c3012d onChatNPC(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
[16:05:25] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: npc
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.2]
	at net.minecraft.server.MinecraftServer.redirect$zjh000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoSuchFieldError: npc
	at com.hiroku.common.quests.listeners.PixelmonHandler.onChatNPC(PixelmonHandler.java:66) ~[PixelmonHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_PixelmonHandler_onChatNPC_NPCChatEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) ~[EventBus.class:?]
	at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.interactWithNPC(NPCChatting.java:142) ~[NPCChatting.class:?]
	at com.pixelmonmod.pixelmon.entities.npcs.EntityNPC.func_184645_a(EntityNPC.java:410) ~[EntityNPC.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:3188) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) ~[PacketPhaseUtil.class:1.12.2-2838-7.2.2]
	at net.minecraft.network.PacketThreadUtil$1.redirect$zld000$impl$redirectToPhaseTracker(SourceFile:540) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

**Comment by Hiroku** [comment]
Fixed
