### ISSUE TITLE
[Broken Quest] Migration of Beauty

### ISSUE THREAD

**Issue by purifiedrabbits** [ObliqueNET/Server#835]
Both starkbot42 and I ran into this same issue while completing the quest Migration of Beauty. Upon completing the battle again an uncommon miniboss Skarmory, the game promptly crashes. When you load back in, the questbook lists 4 tasks: each labeled "a description." Past this point, we cannot progress.

Here is the crash log:

`Time: 10/29/20 2:05 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.pixelmonmod.pixelmon.client.gui.battles.battleScreens.LevelUpScreen.drawScreen(LevelUpScreen.java:103)
	at com.pixelmonmod.pixelmon.client.gui.battles.GuiBattle.func_73863_a(GuiBattle.java:512)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by CenizaRey** [comment]
Hi! You’re better off waiting for a QD to respond but here’s an explanation of your problem.

Whenever you battle a boss pokemon in a quest, it places you into a hidden quest stage which contains all of the variables for each possible outcome of the battle; of which there are 4:

You win
You lose
You forfeit
The battle is ended in an unusual way: i.e. through “/endbattle”

The reason why the stages are all called “a description” is because QDs often don’t bother to name these stages as you’re never actually supposed to see them. This is not only true for ‘Migration of Beauty’, but for most other quests as well.

What’s happened here is, since you crashed, none of the four variables apply to the way in which your battle with the Skarmory boss ended. Since the quest had nowhere to put you, it just left you in the battle stage with no way to progress.

The solution is simple! Just ask any QD online to set you back a stage.

(This comment is for the benefit of anyone else reading who may be having a similar problem with this quest or any other)

**Comment by Soshisen** [comment]
This is a Pixelmon bug that has interfered with the quest system. If either of you have not been helped yet please let me know here or tag me in #support. I, or any QD, can fix the quest part of this problem. As for the rendering error please report that to https://pixelmonmod.com/tracker.php?p=2 along with your logs.
