### ISSUE TITLE
[NuVotifier] Could not set up PluginMessaging

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#948]
`[14:28:19] [Votifier epoll boss/INFO] [nuvotifier]: Votifier enabled on socket /0.0.0.0:PORT.
[14:28:19] [Server thread/ERROR] [nuvotifier]: NuVotifier could not set up PluginMessaging for vote forwarding!
org.spongepowered.api.network.ChannelRegistrationException: Error registering channel "NuVotifier" to Plugin{id=nuvotifier, name=NuVotifier, version=2.7.1, description=Safe, smart, and secure Votifier server plugin, authors=[Ichbinjoe], source=./mods/nuvotifier-2.7.1.jar}
        at org.spongepowered.mod.network.SpongeModNetworkManager.createRawChannel(SpongeModNetworkManager.java:146) ~[SpongeModNetworkManager.class:1.12.2-2838-7.3.0]
        at com.vexsoftware.votifier.sponge.forwarding.SpongePluginMessagingForwardingSink.<init>(SpongePluginMessagingForwardingSink.java:17) ~[SpongePluginMessagingForwardingSink.class:?]
        at com.vexsoftware.votifier.sponge.NuVotifier.loadAndBind(NuVotifier.java:120) ~[NuVotifier.class:?]
        at com.vexsoftware.votifier.sponge.NuVotifier.reload(NuVotifier.java:152) ~[NuVotifier.class:?]
        at com.vexsoftware.votifier.sponge.NuVotifier.onGameReload(NuVotifier.java:193) ~[NuVotifier.class:?]
        at org.spongepowered.common.event.listener.GameReloadEventListener_NuVotifier_onGameReload89.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97) ~[RegisteredListener.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) ~[SpongeModEventManager.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458) ~[SpongeModEventManager.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419) ~[SpongeModEventManager.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467) ~[SpongeEventManager.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249) ~[SpongeImpl.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$10(SpongeCommandFactory.java:629) ~[SpongeCommandFactory.class:1.12.2-2838-7.3.0]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) [ChildCommandElementExecutor.class:1.12.2-2838-7.3.0]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) [CommandSpec.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) [SpongeCommandDispatcher.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.0]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:433) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:398) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.RuntimeException: That channel is already registered
        at net.minecraftforge.fml.common.network.NetworkRegistry.newChannel(NetworkRegistry.java:154) ~[NetworkRegistry.class:?]
        at org.spongepowered.mod.network.SpongeModChannelBinding.<init>(SpongeModChannelBinding.java:52) ~[SpongeModChannelBinding.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.network.SpongeRawChannel.<init>(SpongeRawChannel.java:55) ~[SpongeRawChannel.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.network.SpongeModNetworkManager.createRawChannel(SpongeModNetworkManager.java:144) ~[SpongeModNetworkManager.class:1.12.2-2838-7.3.0]
        ... 22 more`

**Comment by Rasgnarok** [comment]
Tested, doesn't seem to impact vote recording. Will need to look at Velocity networking.

**Comment by Rasgnarok** [comment]
Fixed, network channel should load SV properly.
